PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE iptv_admin (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    username TEXT NOT NULL,
    password TEXT NOT NULL
);

CREATE TABLE iptv_category (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL UNIQUE,
    enable INTEGER NOT NULL DEFAULT 1,
    type TEXT NOT NULL DEFAULT 'user',
    proxy INTEGER NOT NULL DEFAULT 0,
    ua TEXT,
    sort INTEGER,
    rules TEXT,
    list_id INTEGER DEFAULT 0,
    rawcount INTEGER DEFAULT 0
);

-- INSERT INTO iptv_category VALUES(1,'央视频道(自动聚合)',1,'auto',0,'',0,'(?i)CCTV-?(\d+\+?)$',0,0);
-- INSERT INTO iptv_category VALUES(2,'卫视频道(自动聚合)',1,'auto',0,'',1,'卫视',0,0);
INSERT INTO iptv_category VALUES(1,'订阅源1',1,'user',0,'',0,'',0,0);
INSERT INTO iptv_category VALUES(2,'订阅源2',1,'user',0,'',1,'',0,0);

CREATE TABLE iptv_fenlei (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL UNIQUE,
    enable INTEGER NOT NULL DEFAULT 1,
    type TEXT NOT NULL DEFAULT 'user',
    proxy INTEGER NOT NULL DEFAULT 0,
    ua TEXT,
    sort INTEGER,
    rules TEXT,
    list_id INTEGER DEFAULT 0,
    rawcount INTEGER DEFAULT 0
);

INSERT INTO iptv_fenlei VALUES(1,'央视频道',1,'user',0,'',0,'',0,0);
INSERT INTO iptv_fenlei VALUES(2,'卫视频道',1,'user',0,'',1,'',0,0);


CREATE TABLE iptv_category_list (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL UNIQUE,
    enable INTEGER NOT NULL DEFAULT 1,
    url TEXT DEFAULT NULL,
    ua TEXT,
    autocategory INTEGER DEFAULT 0,
    latesttime TEXT DEFAULT NULL,
    repeat INTEGER DEFAULT 0
);

CREATE TABLE iptv_channels (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    url TEXT DEFAULT NULL,
    sort INTEGER,
    status INTEGER NOT NULL DEFAULT 1,
    e_id INTEGER DEFAULT 0,
    c_id INTEGER DEFAULT 0,
    list_id INTEGER DEFAULT 0
);

CREATE TABLE iptv_pindao (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    url TEXT DEFAULT NULL,
    sort INTEGER,
    status INTEGER NOT NULL DEFAULT 1,
    e_id INTEGER DEFAULT 0,
    c_id INTEGER DEFAULT 0,
    list_id INTEGER DEFAULT 0,
    rss_rules TEXT,
    epg_rules TEXT,
    rss_list TEXT,
    epg_list TEXT
);

INSERT INTO iptv_pindao VALUES(1,'CCTV1','',0,1,0,1,0,'CCTV1|CCTV-1|CCTV1综合|CCTV-1综合|CCTV-1 4K','CCTV1|CCTV-1|CCTV1综合|CCTV-1综合|CCTV-1 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(2,'CCTV2','',1,1,0,1,0,'CCTV2|CCTV-2|CCTV2财经|CCTV-2财经|CCTV-2 4K','CCTV2|CCTV-2|CCTV2财经|CCTV-2财经|CCTV-2 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(3,'CCTV3','',2,1,0,1,0,'CCTV3|CCTV-3|CCTV3综艺|CCTV-3综艺|CCTV-3 4K','CCTV3|CCTV-3|CCTV3综艺|CCTV-3综艺|CCTV-3 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(4,'CCTV4','',3,1,0,1,0,'CCTV4|CCTV-4|CCTV4亚洲|CCTV-4亚洲|CCTV-4 4K','CCTV4|CCTV-4|CCTV4亚洲|CCTV-4亚洲|CCTV-4 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(5,'CCTV5','',4,1,0,1,0,'CCTV5|CCTV-5|CCTV5体育|CCTV-5体育|CCTV-5 4K','CCTV5|CCTV-5|CCTV5体育|CCTV-5体育|CCTV-5 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(6,'CCTV5+','',5,1,0,1,0,'CCTV5+|CCTV-5+|CCTV5+体育赛事|CCTV-5+体育赛事|CCTV-5+ 4K','CCTV5+|CCTV-5+|CCTV5+体育赛事|CCTV-5+体育赛事|CCTV-5+ 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(7,'CCTV6','',6,1,0,1,0,'CCTV6|CCTV-6|CCTV6电影|CCTV-6电影|CCTV-6 4K','CCTV6|CCTV-6|CCTV6电影|CCTV-6电影|CCTV-6 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(8,'CCTV7','',7,1,0,1,0,'CCTV7|CCTV-7|CCTV7国防军事|CCTV-7国防军事|CCTV-7 4K','CCTV7|CCTV-7|CCTV7国防军事|CCTV-7国防军事|CCTV-7 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(9,'CCTV8','',8,1,0,1,0,'CCTV8|CCTV-8|CCTV8电视剧|CCTV-8电视剧|CCTV-8 4K','CCTV8|CCTV-8|CCTV8电视剧|CCTV-8电视剧|CCTV-8 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(10,'CCTV9','',9,1,0,1,0,'CCTV9|CCTV-9|CCTV9记录|CCTV-9记录|CCTV-9 4K','CCTV9|CCTV-9|CCTV9记录|CCTV-9记录|CCTV-9 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(11,'CCTV10','',10,1,0,1,0,'CCTV10|CCTV-10|CCTV10科教|CCTV-10科教|CCTV-10 4K','CCTV10|CCTV-10|CCTV10科教|CCTV-10科教|CCTV-10 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(12,'CCTV11','',11,1,0,1,0,'CCTV11|CCTV-11|CCTV11戏曲|CCTV-11戏曲|CCTV-11 4K','CCTV11|CCTV-11|CCTV11戏曲|CCTV-11戏曲|CCTV-11 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(13,'CCTV12','',12,1,0,1,0,'CCTV12|CCTV-12|CCTV12社会于法|CCTV-12社会于法|CCTV-12 4K','CCTV12|CCTV-12|CCTV12社会于法|CCTV-12社会于法|CCTV-12 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(14,'CCTV13','',13,1,0,1,0,'CCTV13|CCTV-13|CCTV13新闻|CCTV-13新闻|CCTV-13 4K','CCTV13|CCTV-13|CCTV13新闻|CCTV-13新闻|CCTV-13 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(15,'CCTV14','',14,1,0,1,0,'CCTV14|CCTV-14|CCTV14少儿|CCTV-14少儿|CCTV-14 4K','CCTV14|CCTV-14|CCTV14少儿|CCTV-14少儿|CCTV-14 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(16,'CCTV15','',15,1,0,1,0,'CCTV15|CCTV-15|CCTV15音乐|CCTV-15音乐|CCTV-15 4K','CCTV15|CCTV-15|CCTV15音乐|CCTV-15音乐|CCTV-15 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(17,'CCTV16','',16,1,0,1,0,'CCTV16|CCTV-16|CCTV16奥林匹克|CCTV-16奥林匹克|CCTV-16 4K','CCTV16|CCTV-16|CCTV16奥林匹克|CCTV-16奥林匹克|CCTV-16 4K','-1','-1');
INSERT INTO iptv_pindao VALUES(18,'CCTV17','',17,1,0,1,0,'CCTV17|CCTV-17|CCTV17农业农村|CCTV-17农业农村|CCTV-17 4K','CCTV17|CCTV-17|CCTV17农业农村|CCTV-17农业农村|CCTV-17 4K','-1','-1');


CREATE TABLE iptv_epg_list (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    url TEXT DEFAULT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    ua TEXT,
    lasttime BIGINT NOT NULL,
    remarks TEXT DEFAULT NULL
);
INSERT INTO iptv_epg_list VALUES(1,'51zmt','http://epg.51zmt.top:8000/e.xml',1,'',0,'51zmt');

CREATE TABLE iptv_epg (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    content TEXT DEFAULT NULL,
    status INTEGER NOT NULL DEFAULT 1,
    remarks TEXT DEFAULT NULL
);
INSERT INTO iptv_epg VALUES(1,'cntv-CCTV1','CCTV1',1,'CCTV1|CCTV-1');
INSERT INTO iptv_epg VALUES(2,'cntv-CCTV2','CCTV2',1,'CCTV2|CCTV-2');
INSERT INTO iptv_epg VALUES(3,'cntv-CCTV3','CCTV3',1,'CCTV3|CCTV-3');
INSERT INTO iptv_epg VALUES(4,'cntv-CCTV4','CCTV4',1,'CCTV4|CCTV-4');
INSERT INTO iptv_epg VALUES(5,'cntv-CCTV5','CCTV5',1,'CCTV5|CCTV-5');
INSERT INTO iptv_epg VALUES(6,'cntv-CCTV5+','CCTV5+',1,'CCTV5+|CCTV-5+');
INSERT INTO iptv_epg VALUES(7,'cntv-CCTV6','CCTV6',1,'CCTV6|CCTV-6');
INSERT INTO iptv_epg VALUES(8,'cntv-CCTV7','CCTV7',1,'CCTV7|CCTV-7');
INSERT INTO iptv_epg VALUES(9,'cntv-CCTV8','CCTV8',1,'CCTV8|CCTV-8');
INSERT INTO iptv_epg VALUES(10,'cntv-CCTV9','CCTV9',1,'CCTV9|CCTV-9');
INSERT INTO iptv_epg VALUES(11,'cntv-CCTV10','CCTV10',1,'CCTV10|CCTV-10');
INSERT INTO iptv_epg VALUES(12,'cntv-CCTV11','CCTV11',1,'CCTV11|CCTV-11');
INSERT INTO iptv_epg VALUES(13,'cntv-CCTV12','CCTV12',1,'CCTV12|CCTV-12');
INSERT INTO iptv_epg VALUES(14,'cntv-CCTV13','CCTV13',1,'CCTV13|CCTV-13');
INSERT INTO iptv_epg VALUES(15,'cntv-CCTV14','CCTV14',1,'CCTV14|CCTV-14');
INSERT INTO iptv_epg VALUES(16,'cntv-CCTV15','CCTV15',1,'CCTV15|CCTV-15');
INSERT INTO iptv_epg VALUES(17,'cntv-CCTV16','CCTV16',1,'CCTV16|CCTV-16');
INSERT INTO iptv_epg VALUES(18,'cntv-CCTV17','CCTV17',1,'CCTV17|CCTV-17');

CREATE TABLE iptv_meals (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    content TEXT DEFAULT NULL,
    status INTEGER NOT NULL DEFAULT 1
);
INSERT INTO iptv_meals VALUES(1000,'默认套餐','央视频道(自动聚合)_卫视频道(自动聚合)',1);
INSERT INTO iptv_meals VALUES(1001,'卧室套餐','',1);
CREATE TABLE iptv_users (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name BIGINT NOT NULL,
    mac TEXT NOT NULL,
    deviceid TEXT NOT NULL,
    model TEXT NOT NULL,
    ip TEXT NOT NULL,
    region TEXT DEFAULT NULL,
    exp BIGINT NOT NULL,
    vpn INTEGER NOT NULL DEFAULT 0,
    idchange INTEGER NOT NULL DEFAULT 0,
    author TEXT DEFAULT NULL,
    authortime BIGINT NOT NULL DEFAULT 0,
    status INTEGER NOT NULL DEFAULT -1,
    lasttime BIGINT NOT NULL,
    marks TEXT DEFAULT NULL,
    meal INTEGER NOT NULL DEFAULT 1000
);
CREATE TABLE IF NOT EXISTS "iptv_movie"  (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,`name` text,api TEXT DEFAULT NULL,`state` integer);
COMMIT;
