name: Build and Push Docker Image

on:
  push:
    tags:
      - '*'             # 任意 tag 都会触发
  workflow_dispatch:     # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 登录 Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. 设置 Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. 获取 tag 名作为镜像版本
      - name: Extract tag version
        id: vars
        run: echo "IMAGE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV
      
      # 5. 写入版本号到文件
      - name: Write version to file
        run: |
          echo "${{ env.IMAGE_VERSION }}" > Version

      # 6. 构建并推送镜像
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/386
          tags: |
            fangguisheng/iptv:latest
            fangguisheng/iptv:${{ env.IMAGE_VERSION }}
